apps/common/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
app_name = "common"

urlpatterns = [
    path("", index, name="index"),
    path("donors_list/<int:myid>/", donors_list, name="donors_list"),
    # path("donors_details/<int:myid>/", views.donors_details, name="donors_details"),
    path("home", home, name="home"),
    path("request_blood/", request_blood, name="request_blood"),
    path("accepted_request/", accepted_request, name="accepted_request"),
    path("see_all_request/", see_all_request, name="see_all_request"),
    path("become_donor/", become_donor, name="become_donor"),
    path("about/", about , name="about"),
    path("login_user/", login_user , name="login_user"),
    path("blood_group/", blood_group , name="blood_group"),
    path('profile/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('change_status/', change_status, name='change_status'),
    path('blood_sched/', blood_sched, name='blood_sched'),
    path('contact/', contact, name='contact'),
    path('admin_base/', admin_base, name='admin_base'),
    path('home_admin/', home_admin, name='home_admin'),
    path('donate_form/', donate_form, name='donate_form'),
    path('about_admin/', about_admin, name='about_admin'),
    path('cert/', cert, name='cert'),
    # path("login/", views.Login, name="login"),
    # path("logout/", views.Logout, name="logout"),
    # path('profile/', views.profile, name='profile'),
    # path('edit_profile/', views.edit_profile, name='edit_profile'),
    # path('change_status/', views.change_status, name='change_status'),
    
    #functions
    path("get_request_data", get_request_data , name="get_request_data"),
    path("view_donor_details", view_donor_details , name="view_donor_details"),
    path("logout", logout_user, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bdms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', 'common_links')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_admin.html
{% extends './admin_base.html' %}

{% load static %}

{% block content %}

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="index.html">Home</a></li>
          <li>About Us</li>
        </ol>
        <h2>About Us</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
     <section id="about" class="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <img src="{% static 'assets/img/slide/about.png'%}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>About Us</h3>
            <p class="fst-italic">
              Blood Donation is important for people in urgent need of it which can save millions of patients. 
              Here Blood Donation Management System for Red Cross was developed for an easy access to all users. The main objective of this project is to create a platform where the people or patients in need of the blood can easily find a donor of the same blood group. 
              This connects the donors and the recipients.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> The patients in need of the blood are able to request for the blood.</li>
              <li><i class="bi bi-check-circle"></i> Users can register themselves to become a donor. </li>
              <li><i class="bi bi-check-circle"></i> All users are also able to see all the donors list according to different blood groups as well as the list of all the requested blood by different users or patients.</li>
            </ul>
          </div>
        </div>
      </div>
    </section><!-- End About Section -->

    <!-- ======= Members Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container">

        <div class="section-title">
          <h2>Members</h2>
          <p>Group 4: Blood Donation Management System for Red Cross</p>
        </div>

        <div class="row">

          <div class="col-lg-6">
            <div class="testimonial-item">
              <img src="{% static 'assets/img/testimonials/lance.jpg' %}" class="testimonial-img" alt="">
              <h3>Laurence Paul Bernardo</h3>
              <h4>Project Leader & Back-end Developer</h4>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mt-4 mt-lg-0">
              <img src="{% static 'assets/img/testimonials/lea.jpg' %}" class="testimonial-img" alt="">
              <h3>Lea Marie Angeles</h3>
              <h4>Front-End Head Developer</h4>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mt-4">
              <img src="{% static 'assets/img/testimonials/giesel.jpg' %}" class="testimonial-img" alt="">
              <h3>Giesel Batoon</h3>
              <h4>Front-End Developer & Documentation</h4>
              <p>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mt-4">
              <img src="{% static 'assets/img/testimonials/albert.jpg' %}" class="testimonial-img" alt="">
              <h3>Albert Venie Bufete</h3>
              <h4>Back-End Developer & Graphic Design</h4>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mt-4">
              <img src="{% static 'assets/img/testimonials/sean.jpg' %}" class="testimonial-img" alt="">
              <h3>Sean Kyle Emmanuel Juruena</h3>
              <h4>Back-End Developer</h4>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mt-4">
              <img src="{% static 'assets/img/testimonials/marlon.jpg' %}" class="testimonial-img" alt="">
              <h3>Marlon Rellama</h3>
              <h4>Front-End Developer</h4>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Members Section -->

  </main><!-- End #main -->






{% endblock content %}

{% block script %}
    
{% endblock script %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Red Cross Blood Donation System</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
      
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
      
        <!-- Vendor CSS Files -->
        <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
        <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <!-- Template Main CSS File -->
        <link href="{% static 'assets/css/style1.css' %}" rel="stylesheet">
        
        <!-- endinject -->
        <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1><a href="index.html">BDMS</a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="active" href="{% url 'common:home' %}">Home</a></li>
          <li><a href="{% url 'common:about' %}">About</a></li>
          <li class="dropdown"><a href="#"><span>Services</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'common:request_blood' %}">Request Blood</a></li>
              <li><a href="{% url 'common:become_donor' %}">Become Donor</a></li>
              <li><a href="{% url 'common:blood_group' %}">Donor's List</a></li>
            </ul>
          </li>
          <li><a href="{% url 'common:contact' %}">Contact</a></li>
          {% if loggedIn %}
            <li class="dropdown"><a href="#"><span>{{ username }}</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li><a href="{% url 'common:profile' %}">Profile</a></li>
                <li><a type="button" id="logout">Logout</a></li>
              </ul>
          {% else %}
            <li><a href="{% url 'common:login_user' %}">Login</a></li>
            <li hidden><a type="button" id="logout">Logout</a></li>
          {% endif %}
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->
  <!-- partial -->
  {% block content %} {% endblock content %}
  <!-- partial -->
<!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a class="active" href="{% url 'common:home' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'common:about' %}">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'common:request_blood' %}">Request Blood</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'common:become_donor' %}">Become Donor</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'common:blood_group' %}">Donor's List</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              37 EDSA corner Boni Avenue,<br>
              Barangka-Ilaya,<br>
              Mandaluyong City 1550<br><br>
              <strong>Phone:</strong> (02) 8790-2300 <br>
              local 931/932/935<br>
              <strong>Email:</strong>communication@redcross.org.ph<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Blood Donation Management for Red Cross</h3>
            <p>Blood Donation is important for people in urgent need of it which can save millions of patients. Here Blood Donation Management System for Red Cross was developed for an easy access to all users. </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Blood Donation Management System for Red Cross</span></strong>. All Rights Reserved 2022.
      </div>
      <div class="credits">
      </div>
    </div>
  </footer><!-- End Footer -->
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter.js'%}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>
  <script>
    let logout = document.getElementById("logout");
    logout.addEventListener('click', function() {
      $.ajax({
        url:'/logout',
        data:{
          'logout': true,
        },
        success: function(data){
          if(data.success){
            console.log(data.success)
            location.reload();
          }
        }
      }); 
    });

  </script>
  {% block script %}
  {% endblock script %}
</body>
</html>

templates/blood_group.html
{% extends './base.html' %}

{% load static %}

{% block content %}

<div class="container">
  <h3><i style="font-weight: bold;">Available Donors According To Blood Group</i></h3>
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for i in all_group %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm border-danger">
                  <div class="card-body">
                    <h3 class="card-text">Blood Group: {{i.name}}</h3>
                    <h3 class="card-text">Total Donor: {{i.total}}</h3>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <a href="/donors_list/{{i.id}}/" class="btn btn-sm btn-outline-danger" style="color:black;">View All Donors</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
    
{% endblock script %}

templates/contact.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Contact</li>
        </ol>
        <h2>Contact</h2>
      </div>
    </section><!-- End Breadcrumbs -->

  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container">

      <div class="row">
        <div class="col-lg-6">
          <div class="info-box mb-4">
            <i class="bx bx-map"></i>
            <h3>Our Address</h3>
            <p>37 EDSA corner Boni Avenue,<br>
                Barangka-Ilaya,<br>
                Mandaluyong City 1550</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="info-box  mb-4">
            <i class="bx bx-envelope"></i>
            <h3>Email Us</h3>
            <p>communication@redcross.org.ph</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="info-box  mb-4">
            <i class="bx bx-phone-call"></i>
            <h3>Call Us</h3>
            <p>(02) 8790-2300<br>
                local 931/932/935</p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 ">
          {% comment %} <iframe class="mb-4 mb-lg-0" src="https://goo.gl/maps/MH9xgQFF9FxmMwCF8" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe> {% endcomment %}
          <div class="mapouter"><div class="gmap_canvas"><iframe class="mb-4 mb-lg-0" id="gmap_canvas" src="https://maps.google.com/maps?q=37%20EDSA,%20corner%201550%20Boni%20Ave,%20Mandaluyong&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" style="border:0; width: 100%; height: 384px;"></iframe><a href="https://fmovies-online.net"></a><br></style></div></div>
        </div>
        <div class="col-lg-6">
          <form action="forms/contact.php" method="post" role="form" class="php-email-form">
            <div class="row">
              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group mt-3">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div>
      </div>
    </div>
  </section><!-- End Contact Section -->
{% endblock content %}
{% block script %}
{% endblock script %}

templates/edit_profile.html
{% extends './base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
<div class="row mt-1">
    <div class="form-group col-md-12">
        <label><i style="font-weight: bold;">Username</i></label>
        <input type="text" class="form-control" name="username" id="username" value="{{user}}" readonly>
    </div>
</div>
 
<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">First Name</i></label>
        <input type="text" class="form-control" name="first_name" id="first_name" value="{{request.user.first_name}}" readonly>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Last Name</i></label>
        <input type="text" class="form-control" name="last_name" id="last_name" value="{{request.user.last_name}}" readonly>
    </div>
</div>
 
<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Email ID</i></label>
        <input type="email" class="form-control" name="email" id="email" value="{{request.user.email}}">
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Contact Number</i></label>
        <input type="tel" class="form-control" name="phone" id="phone" value="{{donor_profile.phone}}">
    </div>
</div>
 
<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">State</i></label>
        <input type="text" class="form-control" name="state" id="state" value="{{donor_profile.state}}">
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">City</i></label>
        <input type="text" class="form-control" name="city" id="city" value="{{donor_profile.city}}">
    </div>
</div>
 
<div class="row mt-1">
    <div class="form-group col-md-12">
        <label><i style="font-weight: bold;">Address</i></label>
        <textarea class="form-control" id="address" name="address" rows="3">{{donor_profile.address}}</textarea>
    </div>
</div>
 
<div class="row mt-2">
<div class="form-group col-md-6">
    <label><i style="font-weight: bold;">Gender</i></label>
    <input type="text" class="form-control" name="gender" value="{{donor_profile.gender}}" readonly>
  </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Blood Group</i></label>
        <input type="text" class="form-control" name="blood_group" value="{{donor_profile.blood_group}}" readonly>
    </div>
</div>
 
<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Profile Photo</i><a href="{{donor_profile.image.url}}">Click here to view the current profile <picture></picture></a></label>
        <input type="file" class="form-control" id="image" name="image">
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Date Of Birth</i></label>
        <input type="date" class="form-control" id="date" name="date" value="{{donor_profile.date_of_birth}}" readonly>
    </div>
</div>
 <br>
<button type="submit" class="btn btn-primary">Update Profile</button>
<br>
</form>
<br>
</div>

{% endblock content %}
{% block script %}
{% endblock script %}

templates/home.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<!--DITO LALAGAY BODY-->
  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide 1 -->
          <div class="carousel-item active" style="background: url({% static 'assets/img/slide/image3.png'%})">
          </div>
          <!-- Slide 2 -->
          <div class="carousel-item" style="background: url({% static 'assets/img/slide/pic2.jpg'%})">
          </div>
          <!-- Slide 3 -->
          <div class="carousel-item" style="background: url({% static 'assets/img/slide/pic3.jpg'%})">
          </div>
        </div>
        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">
    <!-- ======= Featured Section ======= -->
    <section id="featured" class="featured">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="icon-box">
              <i class="bi bi-card-checklist"></i>
              <h3><a href="">Request Blood</a></h3>
              <p>Easy and accessible online request blood that users may fill out.</p>
            </div>
          </div>
          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi"></i>
              <i class="bx bx-donate-blood"></i>
              <h3><a href=""><br>Become Blood Donor</a></h3>
              <p>Become a blood donor with easy registration and save lives.</p>
            </div>
          </div>
          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi"></i>
              <i class="bx bx-book-content"></i>
              <h3><a href=""><br>Contact</a></h3>
              <p>An easy accessible hotline number for Philippine Red Cross.</p>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Featured Section -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <img src="{% static 'assets/img/slide/about.png'%}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>About Us</h3>
            <p class="fst-italic">
              Blood Donation is important for people in urgent need of it which can save millions of patients. 
              Here Blood Donation Management System for Red Cross was developed for an easy access to all users. The main objective of this project is to create a platform where the people or patients in need of the blood can easily find a donor of the same blood group. 
              This connects the donors and the recipients.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> The patients in need of the blood are able to request for the blood.</li>
              <li><i class="bi bi-check-circle"></i> Users can register themselves to become a donor. </li>
              <li><i class="bi bi-check-circle"></i> All users are also able to see all the donors list according to different blood groups as well as the list of all the requested blood by different users or patients.</li>
            </ul>
          </div>
        </div>
      </div>
    </section><!-- End About Section -->

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">
        <div class="row">
          <h1 align="center"><b>How to Donate Blood</b><br><br></h1>
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-bookmark-plus"></i></div>
              <h4><a href="">How often can a person donate?</a></h4>
              <p>A healthy individual may donate every three months.</p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-bookmark-plus"></i></div>
              <h4><a href="">Will donating blood make a person weak?</a></h4>
              <p>No, it will not make you weak. Donating 450cc will not cause any ill effects or weakness. The human body has the capacity to compensate with the new fluid volume. Further, the bone marrow is stimulated to produce new blood cells which in turn makes the blood forming organs function more effectively.</p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-lg-0">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-bookmark-plus"></i></div>
              <h4><a href="">Can a person who has tattoo or body piercing still donate blood?</a></h4>
              <p>If the tattooing procedure or the piercing was done a year ago, he/she may donate. This is also applicable to acupuncture, and other procedures involving needles.</p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-bookmark-plus"></i></div>
              <h4><a href="">How long will it take to donate blood?</a></h4>
              <p>The whole process of blood donation, from the registration up to the recovery, will only take an average of 30 minutes.

                The blood extraction will take about 5-10 minutes. The blood volume will start replenishing within 24 hours. Theoretically, by the end of the month, the body will have the blood status before the blood donation.</p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-bookmark-plus"></i></div>
              <h4><a href="">Will I contract disease through blood donation?</a></h4>
              <p>No, we use sterile, disposable needles and syringes.</p>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Services Section -->
  </main>
{% endblock content %}
{% block script %}
{% endblock script %}

templates/index1.html
<div class="container">
    <h1>Available Donors According To Blood Group</h1>
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for i in all_group %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm border-danger">
                  <div class="card-body">
                    <h3 class="card-text">Blood Group: {{i.name}}</h3>
                    <h3 class="card-text">Total Donor: {{i.total}}</h3>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <a href="/request_blood/{{i.id}}/" class="btn btn-sm btn-outline-danger">View All Donors</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
    </div>
</div>